set -x fish_greeting ''
alias folio='cd $HOME/Documentos/folio && git status'
alias folio_back='cd $HOME/Documentos/folio_back && git status'
alias ff='folio'
alias fb='folio_back'
alias st='git status'
alias ys='yarn start'
alias front_new_branch='. $HOME/.scripts/new_branch_front.sh'
alias check='git checkout'
alias checkout='check'
alias stash='git stash'
alias push='git push'
alias fetch='git fetch'
alias pull='git pull'
alias merge='git merge'
alias add='git add'
alias cm='git commit -m'
#alias mastersetup='cd $HOME/.config && ./mastersetup.sh && cd'
alias config='vi $HOME/.config/fish/config.fish'
alias sship='vim $HOME/.config/starship.toml'
alias vim='vi'
alias c='clear'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias dot='dotfiles'
alias tm='bpytop'

alias folio='cd $HOME/Documentos/folio' 
alias front='folio && check dev1/front'
alias back='folio_back && check dev1/backend'
starship init fish | source
